name: Build Android (Kotlin)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK for Kotlin/Gradle
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle (with caching)
        uses: gradle/actions/setup-gradle@v3
      - name: Ensure Gradle wrapper is executable
        run: chmod +x ./gradlew
      - name: Build Debug (Kotlin)
        run: ./gradlew --no-daemon clean :app:assembleDebug --stacktrace --warning-mode all
      - name: Upload APK (Debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
