name: Release Android APK

on:
  workflow_dispatch:
    inputs:
      variant:
        description: "Build variant (release/debug)"
        required: true
        default: "release"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build APK
        run: |
          if [ "${{ github.event.inputs.variant }}" = "release" ]; then
            ./gradlew clean :app:assembleRelease --stacktrace
          else
            ./gradlew clean :app:assembleDebug --stacktrace
          fi
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ github.event.inputs.variant }}
          path: |
            app/build/outputs/apk/${{ github.event.inputs.variant }}/app-${{ github.event.inputs.variant }}.apk
      - name: Upload mapping (release only)
        if: ${{ github.event.inputs.variant == 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: mapping-release
          path: app/build/outputs/mapping/release/mapping.txt
